INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Arroz", "15", "Arroz rojo con chícharos y zanahoria", "ST", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Jugo", "15", "naranja natural", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Café de olla", "15", "Calientito y crema ", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Café americano", "18", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Capuchino", "30", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Expresso", "22", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Chocolate", "30", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Leche Caliente", "28", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Té", "15", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Agua pero nescafe", "15", "Descripción del platillo", "EX", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Arroz", "15", "Arroz rojo con chícharos y zanahoria", "ST", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Codito a la crema", "15", "Descripción del platillo", "ST", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Salchichas fritas", "15", "Descripción del platillo", "ST", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Ensalada", "15", "Descripción del platillo", "ST", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Sopa", "15", "Descripción del platillo", "EN", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Consome", "15", "Descripción del platillo", "EN", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Crema de brocoli", "15", "Descripción del platillo", "EN", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Crema de zanahoria", "15", "Descripción del platillo", "EN", "1");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Tortas de papa", "50", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Nuggets de pollo", "50", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Huevos con ejotes", "50", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Croqueta de pollo", "50", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Tacos dorados de pollo", "50", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Pambazo", "35", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Omelet de papa ", "55", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Tortas de espinaca", "55", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Picadillo", "55", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Sopes con quesillo", "55", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Sopes con pollo", "55", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Tortas de pollo en verde", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Chile relleno de queso", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Pollo a la barbacoa c/ensalada de papas", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Tortas de carne en verde", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Enchiladas jaliciences", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Higado encebollado", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Chilaquiles con pollo", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Muslo empanizado con papas", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Chuleta ahumada a la plancha", "60", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Enchiladas verdes", "65", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Alambre de pollo", "65", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Pechuga rellena en crema de chipotle", "65", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Carne de res en asado", "65", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Costilla de puerco en verde con verdolagas", "65", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Pollo con mole", "65", "Descripción del platillo", "GU", "0");
INSERT INTO socorritomixcoacst_platillo (nombre, precio, descripcion, tipo, es_complemento) VALUES ("Enchiladas de mole", "65", "Descripción del platillo", "GU", "0");

