INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Arroz", "Arroz rojo con chícharos y zanahoria", "ST", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Expresso", "Descripción del platillo", "BE", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Agua para nescafe", "Descripción del platillo", "BE", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Codito a la crema", "Descripción del platillo", "ST", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Salchichas fritas", "Descripción del platillo", "ST", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Ensalada", "Descripción del platillo", "ST", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Sopa", "Descripción del platillo", "EN", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Consomé", "Descripción del platillo", "EN", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Crema de brocoli", "Descripción del platillo", "EN", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Crema de zanahoria", "Descripción del platillo", "EN", "1", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Tortas de papa", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Nuggets de pollo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Huevos con ejotes", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Croqueta de pollo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Tacos dorados de pollo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Pambazo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Omelet de papa ", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Tortas de espinaca", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Picadillo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Sopes con quesillo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Tortas de pollo en salsa verde", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Chile relleno de queso", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Pollo a la barbacoa c/ensalada de papas", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Tortas de carne en salsa verde", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Enchiladas jaliciences", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Higado encebollado", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Muslo empanizado con papas", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Chuleta ahumada a la plancha", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Enchiladas verdes", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Alambre de pollo", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Pechuga rellena en crema de chipotle", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Carne de res en asado", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Costilla de puerco en verde con verdolagas", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Pollo con mole", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Enchiladas de mole", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Milanesa", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Pechuga asada", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Empanizada", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Cecina", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Costilla", "Acompañadas con chilaquiles o con sopes(2)", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Pancita", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante) VALUES ("Chilaquiles", "Descripción del platillo", "GU", "0", "0" ,"0");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Jugo", "vaso chico", "BE", "0", "0" ,"0", "D1");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Fruta", "de temporada", "EX", "0", "0" ,"0", "D1");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Molletes", "con pico de gallo", "EX", "0", "0" ,"0", "D2");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Hotcakes", "2 piezas", "EX", "0", "0" ,"0", "D2");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Sopes con pollo", "2 piezas", "EX", "0", "0" ,"0", "D2");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Huevos Al gusto", "Rancheros,con Jamón, al albañil o con longaniza", "GU", "0", "0" ,"0", "D2");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Cereal con Leche", "Descripción", "EX", "0", "0" ,"0", "D2");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Salchipulpos", "Descripción de platillo", "EX", "0", "0" ,"0", "D2");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Té", "taza chica", "BE", "0", "0" ,"0", "D3");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Café de olla", "taza chica", "BE", "0", "0" ,"0", "D3");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Café americano", "taza chica", "BE", "0", "0" ,"0", "D3");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Café con leche", "taza chica", "BE", "0", "0" ,"0", "D3");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Leche Caliente", "taza chica", "BE", "0", "0" ,"0", "D3");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Capuchino", "taza chica", "BE", "0", "0" ,"0", "D3");
INSERT INTO socorritomixcoacst_platillo (nombre, descripcion, tipo, es_complemento, esta_eliminado, es_constante, tipo_desayuno) VALUES ("Chocolate", "taza chica", "BE", "0", "0" ,"0", "D3");

